apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-deployment
spec:
  selector:
    matchLabels:
      app: mysql-db
  serviceName: mysql-db-service
  template:
    metadata:
      labels:
        app: mysql-db
    spec:
      containers:
        - name: mysql-db-image
          image: mysql:5-debian
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: MYSQL_PASSWORD
          ports:
            - name: mysql-db
              containerPort: 3306
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-db-service
spec:
  ports:
    - targetPort: 3306
      port: 3306
  clusterIP: None
  selector:
    app: mysql-db
