apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-nodejs-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nodejs-rolling-update-deployment
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 10
